apiVersion: yugabyte.com/v1alpha1
kind: YBCluster
metadata:
  name: example-ybcluster
  namespace: tmp-smartstore 
spec:
  image:
    repository: yugabytedb/yugabyte
    tag: 2.7.0.0-b17
    pullPolicy: IfNotPresent

  replicationFactor: 3
  master:
    replicas: 3
    masterUIPort: 7000
    masterRPCPort: 7100
    enableLoadBalancer: true
    podManagementPolicy: Parallel
    storage:
      count: 1
      size: 50Gi
      storageClass: standard
    resources:
      requests:
        cpu: 2000m
        memory: 2Gi
      limits:
        cpu: 2000m
        memory: 2Gi
    gflags:
      - key: memory_limit_hard_bytes
        value: "2147483648"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: outreach.io/nodepool
              operator: In
              values:
              - stable-nodes


  tserver:
    replicas: 3
    tserverUIPort: 9000
    tserverRPCPort: 9100
    ycqlPort: 9042
    yedisPort: 6379
    ysqlPort: 5433
    enableLoadBalancer: true
    podManagementPolicy: Parallel
    storage:
      count: 1
      size: 100Gi
      storageClass: standard
    resources:
      requests:
        cpu: 4000m
        memory: 8Gi
      limits:
        cpu: 4000m
        memory: 8Gi
    gflags:
      - key: ysql_num_shards_per_tserver 
        value: "1"
      - key: memory_limit_hard_bytes
        value: "8589934592"
